apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkyNTAzLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJkbUZzWVhoNU1ERXdNakF6T2xaaGJHRjRlVEF4TURJPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson